### ISSUE TITLE
@all-contributors add 

### ISSUE THREAD

**Issue by EXYNOS-999** [M-68/meta_resource#21]
Adding contributors to project.

**Comment by EXYNOS-999** [comment]
@all-contributors add add @VikramxD for content

**Comment by EXYNOS-999** [comment]
@all-contributors please add @VikramxD for content

**Comment by Agrover112** [comment]
Close branch? @EXYNOS-999  Issue done

**Comment by EXYNOS-999** [comment]
@all-contributors please add @notmehul  for content

**Comment by rishistyping** [comment]
@all-contributors add add @binarypheonix  for content and code

**Comment by rishistyping** [comment]
@all-contributors please add @binarypheonix for code, content, data, doc, design, example, ideas, infra, maintenance, platform, question, review, research, tool, test and userTesting
